version: 2.1
commands:
  scan:
    description: |
      Start the scan on a target (website) using Probely.
    parameters:
      api_key:
        default: PROBELY_API_KEY
        description: |
          The Probely API key to use, defined in the PROBELY_API_KEY environment variable.
        type: env_var_name
      api_url:
        default: https://api.probely.com
        description: The URL of Probely's API
        type: string
      target_id:
        description: The id of the target (website) to scan.
        type: string
    steps:
    - run:
        command: |
          # Check if API key is set
          if [ -z "${<< parameters.api_key >>}" ]; then
            echo "NO PROBELY API KEY SET"
            echo "Please set your API key in the << parameters.api_key >> variable"
            exit 1
          fi
          # Check if target id is set
          if [ -z "<< parameters.target_id >>" ]; then
            echo "NO PROBELY TARGET ID SET"
            echo "Please set the target id as a parameter for this orb."
            exit 1
          fi
          curl -X POST \
              -H "Authorization: JWT ${<< parameters.api_key >>}" \
              << parameters.api_url >>/targets/<< parameters.target_id >>/scan_now/
          exit $?
        name: Probely - Starting Security Scan
description: |
  Use Probely to scan your web application for security vulnerabilities.
  Full orb source code: https://github.com/Probely/probely-orb
display:
  home_url: https://probely.com/
  source_url: https://github.com/Probely/probely-orb

executors:
  alpine:
    docker:
    - environment:
        TERM: dumb
      image: cibuilds/base:latest
    resource_class: small

jobs:
  Scan:
    description: Start a scan on a target (website) using Probely.
    executor: alpine
    parameters:
      api_key:
        default: PROBELY_API_KEY
        description: |
          The Probely API key to use, defined in the PROBELY_API_KEY environment variable.
        type: env_var_name
      target_id:
        description: The id of the target (website) to scan.
        type: string
    steps:
    - scan:
        target_id: << parameters.target_id >>

  Test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
          no_output_timeout: 30m
      - run:
          name: Test
          command: yarn test
          no_output_timeout: 30m

  Deploy:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "run deploy command here"
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-test:
    jobs:
      - Test
      - Deploy:
          requires:
            - Test
      - Scan:
          requires:
            - Deploy
          target_id: 36oFYYRFkkuR
